import 'dart:convert';
import 'dart:io';

import 'package:broker_contract/broker_contract.dart';
import 'package:test/test.dart';

/// The DTO the broker actually builds, regenerated by
/// `scripts/contracts/generate-usage-report-sample.ts` and verified current by
/// `scripts/contracts/check.sh`.
///
/// Decoding it here is the cross-language pin. Nothing in the broker's
/// TypeScript references these Dart field names and nothing here references
/// its own, so a rename on either side would otherwise leave both suites green
/// and the client rendering zeros for a year of usage.
Map<String, dynamic> loadSample() {
  final file = File('../../../contracts/generated/usage-report.sample.json');
  expect(
    file.existsSync(),
    isTrue,
    reason: 'run bun run scripts/contracts/generate-usage-report-sample.ts',
  );
  return jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
}

void main() {
  group('UsageReport decodes the broker DTO', () {
    late UsageReport report;

    setUpAll(() => report = UsageReport.fromJson(loadSample()));

    test('window and totals survive the wire', () {
      expect(report.range.from, '2026-08-01');
      expect(report.range.to, '2026-08-31');
      expect(report.range.days, 31);
      expect(report.range.recognized, isTrue);
      expect(report.range.periodResolved, 'custom');

      expect(report.totals.tokens, 19893991786);
      expect(report.totals.requests, 129030);
      expect(report.totals.cost, closeTo(12976.51, 0.001));
      expect(report.totals.tokensIn, 469390032);
      expect(report.totals.tokensOut, 51016889);
      expect(report.totals.cacheHitRate, closeTo(0.9689, 1e-9));
      expect(report.timezone, 'BST');
    });

    test('facets arrive with the values the broker served', () {
      expect(report.hourly!.peakHour, 15);
      expect(report.hourly!.nightShare, closeTo(0.218, 1e-9));
      expect(report.hourly!.nightHours, [22, 23, 0, 1]);
      expect(report.hourly!.buckets.first.hour, 0);
      expect(report.hourly!.buckets.first.tokens, 861148188);

      expect(report.weekday!.peakWeekday, 6);
      expect(report.weekday!.buckets.length, 2);

      expect(report.daily!.length, 2);
      expect(report.daily!.first.date, '2026-08-01');
      expect(report.daily!.first.intensity, 4);

      expect(report.streaks!.longestStreak, 31);
      expect(report.streaks!.activeDays, 31);
      expect(report.firsts!.busiestDay, '2026-08-31');
      expect(report.firsts!.busiestDayTokens, 1097438655);

      expect(report.coverage!.sourceCount, 5);
      expect(report.coverage!.liveSources, ['kilocode', 'mimo']);
      expect(report.insightsUnavailable, isNull);
      expect(report.hasWhenYouWork, isTrue);
    });

    test('tools keep their nulls rather than collapsing to zero', () {
      expect(report.tools.map((tool) => tool.tool), [
        'claude',
        'codex',
        'openclaw',
      ]);
      final claude = report.tools.first;
      expect(claude.label, 'Claude Code');
      expect(claude.sessions, 119);
      expect(claude.requests, 44456);
      expect(claude.coding, isTrue);

      // openclaw has stored tokens and no coding-apps or active-time row. Those
      // cells must stay null so the table em-dashes them: "not measured" and
      // "measured as zero" are different claims.
      final openclaw = report.tools.last;
      expect(openclaw.tokens, 777870272);
      expect(openclaw.coding, isFalse);
      expect(openclaw.requests, isNull);
      expect(openclaw.sessions, isNull);
      expect(openclaw.activeMs, isNull);
    });

    test('models keep the served order rather than being re-sorted', () {
      expect(report.topModelsByTokens.first.name, 'claude-opus-5');
      expect(report.topModelsByTokens.last.name, 'gpt-5.6-sol');
      expect(report.topModelsByCost.first.name, 'claude-opus-5');
    });

    test('no prompt text is decodable from the sample', () {
      expect(
        jsonEncode(loadSample()).contains('display_name'),
        isFalse,
        reason: 'the broker drops it; the sample proves the DTO carries none',
      );
    });
  });

  group('UsageProjectReconciliation', () {
    test('splits the period into three parts that sum to exactly one', () {
      final report = UsageReport.fromJson(loadSample());
      final reconciliation = report.projectReconciliation!;

      expect(
        reconciliation.namedShare +
            reconciliation.unattributedShare +
            reconciliation.gapShare,
        closeTo(1, 1e-12),
      );
      // The gap is the whole point: it dwarfs the in-facet unattributed bucket,
      // and printing only the latter is the defect this type exists to prevent.
      expect(reconciliation.gapShare, greaterThan(0));
      expect(
        reconciliation.gapShare,
        greaterThan(reconciliation.unattributedShare),
      );
      expect(reconciliation.namedShare, closeTo(0.59172, 1e-4));
      expect(reconciliation.unattributedShare, closeTo(0.00771, 1e-4));
      expect(reconciliation.gapShare, closeTo(0.40057, 1e-4));
    });

    test('a facet that covers the period leaves no gap', () {
      const projects = UsageReportProjects(
        rows: [
          UsageReportProjectRow(
            project: 'atlas',
            tokens: 900,
            cost: 1,
            requests: 1,
          ),
        ],
        namesIncluded: true,
        unattributedTokens: 100,
      );
      final reconciliation = UsageProjectReconciliation.of(projects, 1000)!;
      expect(reconciliation.namedShare, closeTo(0.9, 1e-12));
      expect(reconciliation.unattributedShare, closeTo(0.1, 1e-12));
      expect(reconciliation.gapShare, closeTo(0, 1e-12));
    });

    test(
      'rounding that overshoots the total cannot render a negative share',
      () {
        // The three upstream figures are separately rounded sums over one scan,
        // so a window where they cross by a hair must still print a whole list.
        const projects = UsageReportProjects(
          rows: [
            UsageReportProjectRow(
              project: 'atlas',
              tokens: 995,
              cost: 1,
              requests: 1,
            ),
          ],
          namesIncluded: true,
          unattributedTokens: 20,
        );
        final reconciliation = UsageProjectReconciliation.of(projects, 1000)!;
        expect(reconciliation.namedShare, lessThanOrEqualTo(1));
        expect(reconciliation.unattributedShare, greaterThanOrEqualTo(0));
        expect(reconciliation.gapShare, greaterThanOrEqualTo(0));
        expect(
          reconciliation.namedShare +
              reconciliation.unattributedShare +
              reconciliation.gapShare,
          closeTo(1, 1e-12),
        );
      },
    );

    test('an empty period has no reconciliation rather than a zero one', () {
      expect(UsageProjectReconciliation.of(null, 1000), isNull);
      expect(
        UsageProjectReconciliation.of(
          const UsageReportProjects(rows: [], namesIncluded: true),
          0,
        ),
        isNull,
      );
    });
  });

  group('degradation', () {
    test('an older tokdash yields a report with every facet null', () {
      final sample = loadSample();
      for (final facet in [
        'hourly',
        'weekday',
        'daily',
        'projects',
        'streaks',
        'firsts',
        'coverage',
        'timezone',
      ]) {
        sample.remove(facet);
      }
      sample['insightsUnavailable'] = 'unsupported';
      final report = UsageReport.fromJson(sample);

      expect(report.insightsUnavailable, UsageInsightsRefusal.unsupported);
      expect(report.hourly, isNull);
      expect(report.weekday, isNull);
      expect(report.daily, isNull);
      expect(report.projects, isNull);
      expect(report.projectReconciliation, isNull);
      expect(report.hasWhenYouWork, isFalse);
      // Only the facet-fed sections go; the report itself keeps its numbers.
      expect(report.totals.tokens, 19893991786);
      expect(report.tools, hasLength(3));
    });

    test('a refusal this client has never heard of decodes, not throws', () {
      expect(
        UsageInsightsRefusal.fromJson('a-reason-from-a-newer-broker'),
        UsageInsightsRefusal.unknown,
      );
      expect(UsageInsightsRefusal.fromJson(null), isNull);
      expect(
        UsageInsightsRefusal.fromJson('malformed'),
        UsageInsightsRefusal.malformed,
      );
    });

    test('an unrecognized window is never read as agreement', () {
      final sample = loadSample();
      (sample['range']! as Map<String, dynamic>).remove('recognized');
      expect(UsageReport.fromJson(sample).range.recognized, isFalse);
    });

    test('an empty report is empty, and a partial one says so', () {
      final report = UsageReport.fromJson({
        'range': {'from': '2026-08-01', 'to': '2026-08-31', 'recognized': true},
        'totals': {'tokens': 0, 'cost': 0, 'requests': 0},
        'sourceErrors': ['kimi'],
      });
      expect(report.isEmpty, isTrue);
      expect(report.isPartial, isTrue);
      expect(report.sourceErrors, ['kimi']);
    });
  });

  group('UsageReportResponse', () {
    test('a refused read reports no report at all', () {
      const response = UsageReportResponse(
        ok: false,
        baseUrl: 'http://127.0.0.1:55423',
        error: 'GET /api/usage failed: ECONNREFUSED',
      );
      expect(response.report, isNull);
    });

    test('a served read carries the report and its cache provenance', () {
      final response = UsageReportResponse.fromJson({
        'ok': true,
        'baseUrl': 'http://127.0.0.1:55423',
        'cachedAt': 1756000000000,
        'servedFromCache': true,
        'data': loadSample(),
      });
      expect(response.report, isNotNull);
      expect(response.report!.totals.tokens, 19893991786);
      expect(response.servedFromCache, isTrue);
      expect(response.cachedAt, 1756000000000);
    });

    test('a body with no data is unavailable rather than empty', () {
      final response = UsageReportResponse.fromJson({'ok': true});
      expect(response.report, isNull);
    });
  });
}
