// GENERATED by scripts/broker/export-client-contract.ts. DO NOT EDIT.
/// Contract revision compiled into this client.
const int cosyncingClientContractRevision = 12;

/// Oldest broker contract this client can safely drive.
const int cosyncingClientMinimumBrokerRevision = 2;

/// Deterministic identity of the public surface used by this client.
const String cosyncingClientContractSurfaceHash = 'fnv1a32:f2eb77a8';
