#!/usr/bin/env bun
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import {
  BROKER_CONTRACT_REVISION,
  BROKER_CONTRACT_SURFACE_HASH,
  CLIENT_MINIMUM_BROKER_CONTRACT_REVISION,
} from '../../packages/typescript/protocol/src/index.ts';
import { renderClientContract } from './lib/client-contract.ts';

function outputPaths(argv: string[]): { output?: string; dartOutput?: string } {
  const result: { output?: string; dartOutput?: string } = {};
  for (let index = 0; index < argv.length; index += 2) {
    const flag = argv[index];
    const value = argv[index + 1];
    if (!value || (flag !== '--output' && flag !== '--dart-output')) {
      throw new Error(
        'Usage: bun run scripts/broker/export-client-contract.ts '
        + '[--output PATH] [--dart-output PATH]',
      );
    }
    if (flag === '--output') result.output = resolve(value);
    else result.dartOutput = resolve(value);
  }
  return result;
}

function renderDartIdentity(): string {
  const minimumBrokerRevision = CLIENT_MINIMUM_BROKER_CONTRACT_REVISION;
  if (minimumBrokerRevision > BROKER_CONTRACT_REVISION) {
    throw new Error(
      'CLIENT_MINIMUM_BROKER_CONTRACT_REVISION cannot exceed BROKER_CONTRACT_REVISION',
    );
  }
  return `// GENERATED by scripts/broker/export-client-contract.ts. DO NOT EDIT.\n`
    + `/// Contract revision compiled into this client.\n`
    + `const int cosyncingClientContractRevision = ${BROKER_CONTRACT_REVISION};\n\n`
    + `/// Oldest broker contract this client can safely drive.\n`
    + `const int cosyncingClientMinimumBrokerRevision = ${minimumBrokerRevision};\n\n`
    + `/// Deterministic identity of the public surface used by this client.\n`
    + `const String cosyncingClientContractSurfaceHash = '${BROKER_CONTRACT_SURFACE_HASH}';\n`;
}

try {
  const contract = renderClientContract();
  const outputs = outputPaths(process.argv.slice(2));
  if (!outputs.output && !outputs.dartOutput) {
    process.stdout.write(contract);
  }
  for (const [path, content] of [
    [outputs.output, contract],
    [outputs.dartOutput, renderDartIdentity()],
  ] as const) {
    if (!path) continue;
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(path);
  }
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(2);
}
