import 'dart:convert';

import 'package:broker_crypto/broker_crypto.dart';
import 'package:test/test.dart';

void main() {
  group('QR pairing payloads', () {
    test('parses broker QR payload v2', () {
      final payloadJson = jsonEncode({
        'version': 2,
        'brokerId': 'broker-test',
        'pairingId': 'pair_abc',
        'publicKey': 'broker-public',
        'transport': {'kind': 'tailscale-direct', 'url': 'http://host:7734'},
      });
      final uri =
          'cosyncing://pair?payload=${base64UrlNoPadding(utf8.encode(payloadJson))}';

      final payload = QrPairingPayload.parse(uri);

      expect(payload.version, 2);
      expect(payload.brokerId, 'broker-test');
      expect(payload.pairingId, 'pair_abc');
      expect(payload.transport.kind, 'tailscale-direct');
      expect(payload.transport.url, Uri.parse('http://host:7734'));
      expect(payload.canAccept, isTrue);
    });

    test('parses legacy v1 but marks it non-acceptable', () {
      final payloadJson = jsonEncode({
        'version': 1,
        'brokerId': 'broker-test',
        'publicKey': 'broker-public',
        'transport': {'kind': 'tailscale-direct', 'url': 'http://host:7734'},
      });
      final uri =
          'cosyncing://pair?payload=${base64UrlNoPadding(utf8.encode(payloadJson))}';

      final payload = QrPairingPayload.parse(uri);

      expect(payload.version, 1);
      expect(payload.pairingId, isNull);
      expect(payload.canAccept, isFalse);
    });

    test('parses provider-neutral v3 with and without a Broker URL', () {
      for (final brokerUrl in <String?>['https://cosy.example.com', null]) {
        final payloadJson = jsonEncode({
          'version': 3,
          'brokerId': 'broker-test',
          'pairingId': 'pair_abc',
          'publicKey': 'broker-public',
          'transport': {
            'kind': 'broker-url',
            if (brokerUrl != null) 'url': brokerUrl,
          },
        });
        final uri =
            'cosyncing://pair?payload=${base64UrlNoPadding(utf8.encode(payloadJson))}';

        final payload = QrPairingPayload.parse(uri);

        expect(payload.version, 3);
        expect(payload.transport.kind, 'broker-url');
        expect(
          payload.transport.url,
          brokerUrl == null ? isNull : Uri.parse(brokerUrl),
        );
        expect(payload.canAccept, isTrue);
      }
    });
  });

  group('pairing keys', () {
    test('exports Ed25519 identity keys as SPKI and PKCS8 base64url', () async {
      final keys = await PairingCrypto.generateIdentityKeyPair();
      final publicDer = base64UrlDecodeNoPadding(keys.publicKey);
      final privateDer = base64UrlDecodeNoPadding(keys.privateKey);

      expect(keys.algorithm, 'Ed25519');
      expect(publicDer.take(12).toList(), [
        0x30,
        0x2a,
        0x30,
        0x05,
        0x06,
        0x03,
        0x2b,
        0x65,
        0x70,
        0x03,
        0x21,
        0x00,
      ]);
      expect(privateDer.take(16).toList(), [
        0x30,
        0x2e,
        0x02,
        0x01,
        0x00,
        0x30,
        0x05,
        0x06,
        0x03,
        0x2b,
        0x65,
        0x70,
        0x04,
        0x22,
        0x04,
        0x20,
      ]);
    });

    test('exports X25519 exchange keys as SPKI and PKCS8 base64url', () async {
      final keys = await PairingCrypto.generateExchangeKeyPair();
      final publicDer = base64UrlDecodeNoPadding(keys.publicKey);
      final privateDer = base64UrlDecodeNoPadding(keys.privateKey);

      expect(publicDer.take(12).toList(), [
        0x30,
        0x2a,
        0x30,
        0x05,
        0x06,
        0x03,
        0x2b,
        0x65,
        0x6e,
        0x03,
        0x21,
        0x00,
      ]);
      expect(privateDer.take(16).toList(), [
        0x30,
        0x2e,
        0x02,
        0x01,
        0x00,
        0x30,
        0x05,
        0x06,
        0x03,
        0x2b,
        0x65,
        0x6e,
        0x04,
        0x22,
        0x04,
        0x20,
      ]);
    });

    test('unwraps DataKey wrapped with broker-compatible primitives', () async {
      final recipient = await PairingCrypto.generateExchangeKeyPair();
      final dataKey = List<int>.generate(32, (index) => index);

      final wrapped = await PairingCrypto.wrapDataKeyForPeer(
        dataKey: dataKey,
        recipientPublicKey: recipient.publicKey,
      );

      final unwrapped = await PairingCrypto.unwrapDataKey(
        wrapped,
        recipientPrivateKey: recipient.privateKey,
      );

      expect(unwrapped, dataKey);
    });

    test('unwraps broker TypeScript reference vector', () async {
      const recipientPrivateKey =
          'MC4CAQAwBQYDK2VuBCIEIBDFzu-GkzHl4SBrPrSJ7aESoJObwfWej_XF6PethMV_';
      // Generated by the broker's scripts/client/generate-pairing-vector.ts (fixture:
      // packages/typescript/crypto/test-vectors/pairing-datakey-wrap-v1.json). Regenerate there
      // after any wrap label/AAD/algorithm change — never hand-edit these values.
      const wrapped = WrappedDataKey(
        version: 1,
        algorithm: 'X25519-HKDF-SHA256-AES-256-GCM',
        ephemeralPublicKey:
            'MCowBQYDK2VuAyEAAa4doLKRdQ7wSVpkUJ5aWWH7fU0Q8zUjGOvLkWg5n3o',
        nonce: '_cvuDohhG5CTBfNH',
        ciphertext: 'wC5r0KqXo8fg0U215pn_CUFM2r_7fh_2HjnnKGA2_tg',
        tag: 'RroQr2D03M0zWiQ7PVmQlA',
      );

      final unwrapped = await PairingCrypto.unwrapDataKey(
        wrapped,
        recipientPrivateKey: recipientPrivateKey,
      );

      expect(unwrapped, List<int>.generate(32, (index) => 255 - index));
    });
  });
}
