export type AgentId = 'opencode' | 'pi' | 'claude' | 'codex';
export type TraceTier = 'synthetic' | 'adapter-live' | 'product-trace' | 'drift';
export type TracePriority = 'p0' | 'p1' | 'p2';

export interface TraceScenario {
  id: string;
  title: string;
  tier: TraceTier;
  priority: TracePriority;
  agents: AgentId[] | 'all';
  purpose: string;
  steps: string[];
  assertions: string[];
  existingCoverage?: string[];
  gaps?: string[];
}

export const AGENTS: AgentId[] = ['opencode', 'pi', 'claude', 'codex'];

export const TRACE_SCENARIOS: TraceScenario[] = [
  {
    id: 'ST-00',
    title: 'surface and version drift',
    tier: 'drift',
    priority: 'p0',
    agents: 'all',
    purpose: 'Detect upstream command, event, model, tool, and version drift before a user discovers it manually.',
    steps: ['Record binary version.', 'Collect commands, models, modes, tools, event kinds, and documented-only commands.', 'Diff true surface against mapped surface.'],
    assertions: ['No required command disappears.', 'No new event or canonical type is observed without a renderer.', 'Report records version and skipped reasons.'],
    existingCoverage: ['scripts/broker/conformance.ts', 'docs/protocol/adapter-support.md'],
  },
  {
    id: 'ST-01',
    title: 'discover, attach, history, and reattach',
    tier: 'adapter-live',
    priority: 'p0',
    agents: 'all',
    purpose: 'Prove a session can be found, attached, replayed, detached, and reattached without duplicate or missing history.',
    steps: ['Create or select a throwaway session.', 'Attach through broker WebSocket.', 'Capture session, commands, options, and history frames.', 'Detach and reattach.'],
    assertions: ['History arrives before live frames.', 'Message keys dedupe history versus live tail.', 'Received artifacts replay on reattach when the broker still owns the connection.'],
    existingCoverage: ['packages/typescript/broker/test/opencode/test-opencode.ts', 'packages/typescript/broker/test/pi/test-pi.ts', 'packages/typescript/broker/test/codex/resume.ts', 'packages/typescript/adapters/claude/test/test-claude-jsonl.ts', 'scripts/broker/tests_traces/claude-runtime-trace.ts (Claude turn-runtime + timestamps doc-15: per-turn run-summary + sentAt + runtimeTotals replay on Observe attach)', 'packages/typescript/broker/test/claude/test-claude-runtime.ts (run-summary/sentAt/runtimeTotals mapper + tracker + real-data smoke)', 'scripts/broker/tests_traces/claude-workflow-activity-trace.ts (Claude UltraCode/workflow + subagent display: canonical agent-activity kind workflow/subagent replays on attach, no Claude-specific type leaks)', 'packages/typescript/adapters/claude/test/test-claude-activity.ts (subagent/workflow → agent-activity mapping)'],
  },
  {
    id: 'ST-02',
    title: 'cold attach first prompt',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'Catch the first-prompt drop class: a prompt sent on WebSocket open must never vanish silently.',
    steps: ['Open a session.', 'Send a prompt in the WebSocket onopen callback.', 'Record wire frames and backing native transcript.'],
    assertions: ['Prompt persists in native history.', 'User-message and assistant output arrive.', 'No silent no-op or hidden broker error.'],
    existingCoverage: ['OpenCode cold-attach test in packages/typescript/broker/test/opencode/test-opencode.ts'],
  },
  {
    id: 'ST-03',
    title: 'true sync: app to terminal',
    tier: 'product-trace',
    priority: 'p0',
    agents: ['opencode', 'pi', 'codex'],
    purpose: 'Verify the single-owner promise from the phone/web side to the host terminal side.',
    steps: ['Start the true-live owner for the agent.', 'Attach the product UI.', 'Send from the product.', 'Observe the host terminal/session state.'],
    assertions: ['The terminal-owned view sees the prompt and response without resume or refresh.', 'Only one owning agent process/server writes the session.'],
    existingCoverage: ['scripts/broker/tests_traces/opencode-true-sync-trace.ts', 'scripts/broker/tests_traces/opencode-real-tui-trace.ts', 'scripts/broker/tests_traces/pi-bridge-true-sync-trace.ts', 'scripts/broker/tests_traces/pi-real-tui-bridge-trace.ts', 'scripts/broker/tests_traces/codex-true-sync-trace.ts', 'scripts/broker/tests_traces/codex-real-tui-smoke.ts'],
  },
  {
    id: 'ST-04',
    title: 'true sync: terminal to app',
    tier: 'product-trace',
    priority: 'p0',
    agents: ['opencode', 'pi', 'codex'],
    purpose: 'Verify the host terminal can drive the same live session and the app updates without refresh.',
    steps: ['Attach app to a live session.', 'Send a prompt directly through the agent terminal or native API.', 'Record app frames and UI state.'],
    assertions: ['Terminal prompt renders as a right-side user-message.', 'No duplicate left-side echo.', 'Assistant stream reaches the app live.'],
    existingCoverage: ['scripts/broker/tests_traces/opencode-true-sync-trace.ts', 'scripts/broker/tests_traces/opencode-real-tui-trace.ts', 'OpenCode direct prompt user-message test', 'scripts/broker/tests_traces/pi-bridge-true-sync-trace.ts', 'scripts/broker/tests_traces/pi-real-tui-bridge-trace.ts', 'scripts/broker/tests_traces/codex-true-sync-trace.ts', 'scripts/broker/tests_traces/codex-real-tui-smoke.ts'],
  },
  {
    id: 'ST-05',
    title: 'late join during stream',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'A phone opened mid-answer must receive the already-streamed text, not only future tokens.',
    steps: ['Start a long answer with client A attached.', 'Attach client B after the answer has started.', 'Compare reconstructed assistant text.'],
    assertions: ['Client B receives pre-join text.', 'Final A and B transcript text match within a small tolerance.'],
    existingCoverage: ['OpenCode late-join test', 'Retired Claude channel permission trace (channel sync remains unsupported; keep late-join permission replay covered before any future live Claude bridge is claimed)'],
  },
  {
    id: 'ST-06',
    title: 'streaming lanes and keys',
    tier: 'adapter-live',
    priority: 'p0',
    agents: 'all',
    purpose: 'Keep answer, thinking, user messages, tool calls, and tool results in stable keyed lanes.',
    steps: ['Drive text, reasoning, and multi-turn prompts.', 'Reconstruct UI text from delta and text frames.', 'Reattach after completion.'],
    assertions: ['Thinking never leaks into model-output.', 'Distinct turns do not collapse into one bubble.', 'Snapshots do not duplicate streamed deltas.'],
    existingCoverage: ['OpenCode reasoning/stream tests', 'Pi multi-turn key test', 'Claude JSONL synthetic mapper'],
  },
  {
    id: 'ST-07',
    title: 'status and roster state',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'Ensure roster and session header state match real activity, not stale heuristics.',
    steps: ['Attach a session.', 'Start a turn.', 'Trigger needs-input.', 'Finish or reject the turn.', 'Detach.'],
    assertions: ['Roster transitions idle -> working -> needs-input -> idle.', 'Live bridge sessions show attachMode live.', 'Stale busy state ages out only where designed.'],
    existingCoverage: ['OpenCode status tests', 'Codex permission roster test', 'Claude freshnessGate unit test'],
  },
  {
    id: 'ST-08',
    title: 'prompt queue, steer, and ordering',
    tier: 'adapter-live',
    priority: 'p0',
    agents: 'all',
    purpose: 'Prompts sent while busy must be visible, ordered, and delivered with the agent-specific streaming-safe mechanism.',
    steps: ['Start a long turn.', 'Send multiple prompts and a command while busy.', 'Record native order and broker frames.'],
    assertions: ['User sees queued or echoed prompts.', 'Native transcript order matches send order.', 'Pi bridge busy sends use deliverAs steer.'],
    existingCoverage: ['OpenCode rapid prompt order', 'Pi bridge queue deliverAs tests'],
  },
  {
    id: 'ST-09',
    title: 'stop and abort',
    tier: 'adapter-live',
    priority: 'p0',
    agents: 'all',
    purpose: 'Stop must interrupt the active turn, clear running state, and leave the transcript consistent.',
    steps: ['Start a long turn.', 'Run stop/abort from the app.', 'Reattach.'],
    assertions: ['Running state clears.', 'No dangling pending prompt or unclosed WebSocket.', 'History replay reflects the interrupted state.'],
    existingCoverage: ['OpenCode stop accepted test', 'Pi abort command path', 'Codex turn lifecycle tests'],
  },
  {
    id: 'ST-10',
    title: 'compact and compaction boundary',
    tier: 'adapter-live',
    priority: 'p0',
    agents: 'all',
    purpose: 'Compact must not block the socket and must mark the rewritten context boundary.',
    steps: ['Create enough history.', 'Run compact.', 'Keep sending/receiving frames while compact runs.', 'Reattach.'],
    assertions: ['Command returns a notice quickly.', 'Completion or history-reset is visible.', 'Injected compact summaries do not render as normal user prompts.'],
    existingCoverage: ['OpenCode compact fast notice', 'Claude compact_boundary mapper', 'Pi compact command mapping'],
    gaps: ['OpenCode compaction part marker still needs product trace coverage.'],
  },
  {
    id: 'ST-11',
    title: 'undo redo and history reset',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'Out-of-band transcript mutation must resync every attached client.',
    steps: ['Create at least two turns.', 'Undo from the app.', 'Redo from the app.', 'Repeat via native terminal/API if available.'],
    assertions: ['Clients receive history-reset or equivalent snapshot.', 'Removed messages disappear.', 'Restored messages reappear without duplicates.'],
    existingCoverage: ['OpenCode app undo/redo and CLI revert sync tests'],
    gaps: ['Pi/Codex/Claude session-tree equivalents need agent-specific mappings.'],
  },
  {
    id: 'ST-12',
    title: 'commands, templates, skills, and spaced names',
    tier: 'drift',
    priority: 'p0',
    agents: 'all',
    purpose: 'Every executable command the user expects must be surfaced and executable with the exact name.',
    steps: ['Collect command palette.', 'Run built-ins.', 'Run a template or skill command.', 'Run a command whose name contains spaces where supported.'],
    assertions: ['Commands frame contains built-ins and dynamic commands.', 'Longest-name parsing sends correct command and args.', 'Command feedback uses notice, not error styling.'],
    existingCoverage: ['OpenCode command tests', 'Pi get_commands conformance', 'Claude/Codex command scans', 'scripts/broker/tests_traces/codex-surface-contract-trace.ts'],
  },
  {
    id: 'ST-13',
    title: 'model, agent, mode, and reasoning controls',
    tier: 'adapter-live',
    priority: 'p1',
    agents: 'all',
    purpose: 'Picker data and per-prompt overrides must use the agent surface correctly.',
    steps: ['Capture options frame.', 'Send a prompt with model/mode/agent override.', 'Verify native session metadata and response.'],
    assertions: ['Current model is always present in options.', 'Invalid model errors surface.', 'Agent/mode override does not silently no-op.'],
    existingCoverage: ['OpenCode model/agent tests', 'Pi model list and set_model conformance', 'scripts/broker/tests_traces/pi-display-trace.ts (Pi bridge model/effort/activity + model options in real app)', 'Codex config/model probe', 'scripts/broker/tests_traces/codex-surface-contract-trace.ts', 'Claude wrapper model tests'],
  },
  {
    id: 'ST-14',
    title: 'permissions and approvals',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'Approval gates must block the right operation, replay while pending, and resolve through the dedicated channel.',
    steps: ['Trigger a safe tool approval.', 'Attach a second client while pending.', 'Approve, reject, and approve-session where supported.'],
    assertions: ['Permission card contains action and affected resource.', 'Roster shows needs-input.', 'Decision resolves the pending request and does not send as a prompt.'],
    existingCoverage: ['scripts/broker/tests_traces/opencode-true-sync-trace.ts', 'scripts/broker/tests_traces/opencode-real-run-drive-trace.ts (private run auto-reject boundary)', 'scripts/broker/tests_traces/opencode-app-answer-real-tui-trace.ts (L3 pass 2026-06-23; session labeled qwen but TUI used MiniMax)', 'OpenCode permission test', 'Codex approval replay test', 'scripts/broker/tests_traces/codex-app-answer-real-tui-trace.ts (L3 pass 2026-06-24 on gpt-5.3-codex-spark/low; qwen3.6-27B-FP8 rejected by Codex ChatGPT-account backend)', 'Claude observe read-only permission mapping', 'Retired Claude channel permission traces (channel sync remains unsupported because current runtime evidence only honors replies from allowlisted channels; Claude control = Observe+Drive)','scripts/broker/tests_traces/pi-bridge-true-sync-trace.ts', 'scripts/broker/tests_traces/pi-app-answer-real-tui-trace.ts (L3 pass 2026-06-23 on vllm-hpc/qwen3.6-27B-FP8)', 'scripts/broker/tests_traces/codex-surface-contract-trace.ts', 'scripts/broker/tests_traces/codex-true-sync-trace.ts'],
  },
  {
    id: 'ST-15',
    title: 'question prompts and blocking dialogs',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'Agent questions, extension dialogs, and free-text prompts must not hang or be answered through the wrong path.',
    steps: ['Trigger select, multi-select, and free-text questions.', 'Attach while pending.', 'Answer and reject where supported.'],
    assertions: ['Question card renders all questions.', 'Answer uses the native question channel.', 'Unknown blocking dialogs cancel or surface instead of hanging forever.'],
    existingCoverage: ['OpenCode question tests', 'scripts/broker/tests_traces/codex-app-answer-trace.ts (Codex DOM question answer)', 'scripts/broker/tests_traces/codex-surface-contract-trace.ts', 'Pi extension_ui_request mapping', 'scripts/broker/tests_traces/claude-observe-question-trace.ts (Claude OBSERVE: a blocked AskUserQuestion surfaces the REAL question read-only, not a generic "blocked in terminal" notice; a genuine permission falls back to the notice)', 'packages/typescript/adapters/claude/test/test-claude-questions.ts (observe getPending surfaces the unanswered question)'],
  },
  {
    id: 'ST-16',
    title: 'retry, rate limit, and unreachable provider',
    tier: 'adapter-live',
    priority: 'p0',
    agents: 'all',
    purpose: '429, provider-auth, bogus model, dead API, and transient retry states must produce visible status or error.',
    steps: ['Run a dead-provider session.', 'Run a bogus model/provider prompt.', 'Inject or replay a rate-limit/error transcript shape.'],
    assertions: ['Retry appears as running status with detail.', 'Final failure emits error.', 'Session does not appear silently idle or frozen.'],
    existingCoverage: ['OpenCode dead-provider retry test', 'OpenCode bogus model error test', 'Claude 429 synthetic JSONL', 'Pi auto_retry mapping'],
  },
  {
    id: 'ST-17',
    title: 'bash and python execution display',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'Shell/script tool execution must be understandable on the phone: command title, stdout/stderr, exit code, truncation, and running state.',
    steps: ['Ask the agent to run bash echo.', 'Ask it to run a Python one-liner or script.', 'Run a non-zero command.', 'Run an output-heavy command.'],
    assertions: ['Tool-call card appears before result.', 'Tool-result shows output, title, exitCode, isError, and truncated flag when present.', 'Long titles do not overflow mobile layout.'],
    existingCoverage: ['OpenCode bash enrichment test', 'scripts/broker/tests_traces/opencode-real-run-drive-trace.ts', 'Pi tool-result enrichment tests', 'Claude Bash mapper test', 'Codex exec_command test'],
  },
  {
    id: 'ST-18',
    title: 'edit, write, patch, read, and search display',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'File-changing and file-reading tools must show path, title, diff, additions, deletions, and truncation without mislabeling non-file tools.',
    steps: ['Create a file.', 'Edit it.', 'Read it with truncation where possible.', 'Search a directory.', 'Reattach.'],
    assertions: ['Create/edit results show correct path and diffstat.', 'Read shows path and truncation.', 'Grep/search directory path is not shown as an edited file.'],
    existingCoverage: ['Pi/Claude tool-result enrichment unit tests', 'OpenCode tool result tests'],
  },
  {
    id: 'ST-19',
    title: 'user to agent file input',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'Uploaded files must reach the agent in the same turn and be readable byte-exactly.',
    steps: ['Upload one text file.', 'Upload multiple files with a prompt.', 'Upload an image/file with tricky names.', 'Ask the agent to quote contents.'],
    assertions: ['Inbox writes exact bytes.', 'Prompt references the actual sanitized path.', 'Agent can read every file.', 'Multi-file upload creates one user turn.'],
    existingCoverage: ['OpenCode MIL file tests', 'Pi file upload tests', 'Codex file input test'],
  },
  {
    id: 'ST-20',
    title: 'agent to user file artifacts',
    tier: 'product-trace',
    priority: 'p0',
    agents: ['opencode', 'pi'],
    purpose: 'Session-qualified agent-produced files must surface, persist across reattach, and be safe to open.',
    steps: ['Deliver through the native session-bound route.', 'Rewrite the same filename.', 'Attempt symlink escape.', 'Send an HTML artifact with local assets.'],
    assertions: ['Only the producing session receives the artifact.', 'Rewrites remain distinct versions for that owner.', 'Symlinks and absolute path leaks are blocked.', 'HTML local assets are bundled.'],
    existingCoverage: ['OpenCode send_file and HTML bundle tests', 'Pi bridge send-file tests', 'broker session-isolation regression suite'],
    gaps: ['Claude maps existing SendUserFile transcript records but local CLI/Drive exposes no callable tool; Codex has no exact session-qualified producer route.'],
  },
  {
    id: 'ST-21',
    title: 'native send-file tools',
    tier: 'product-trace',
    priority: 'p1',
    agents: ['opencode', 'pi'],
    purpose: 'Native session-qualified send-file mechanisms must produce the canonical file-artifact UI.',
    steps: ['Trigger the agent native send-file tool if available.', 'Send a non-deliverable file that only native send-file should surface.'],
    assertions: ['A file-artifact appears with correct bytes.', 'The tool-result is not merely a bare chip.', 'Unsupported agents explicitly skip with reason.'],
    existingCoverage: ['OpenCode MIL send_file test', 'Pi bridge send-file test'],
    gaps: ['Claude Code and Codex remain unavailable until each has an exact session-qualified producer route.'],
  },
  {
    id: 'ST-22',
    title: 'session lifecycle: new, resume, fork, clone, delete, rename, export',
    tier: 'product-trace',
    priority: 'p1',
    agents: 'all',
    purpose: 'Session-level operations must update roster, transcript, and attached clients without orphaning sockets.',
    steps: ['Create new session.', 'Rename where supported.', 'Fork/clone/resume where supported.', 'Delete current session.', 'Export transcript/artifact.'],
    assertions: ['Roster updates without waiting for a full manual refresh.', 'Deleted attached sessions show a clear ended/error frame.', 'Export produces a downloadable artifact or explicit unsupported notice.'],
    existingCoverage: ['Pi bridge reload/new/resume/fork teardown test', 'OpenCode new session and delete routes partially tested'],
  },
  {
    id: 'ST-23',
    title: 'multi-client lifecycle and leak checks',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'Attach/detach churn must not leak processes, sockets, watchers, or phantom clients.',
    steps: ['Attach two clients.', 'Detach one.', 'Detach both.', 'Reattach inside and after grace windows.', 'Inspect process list and broker state.'],
    assertions: ['One owner serves multiple clients.', 'Owner is disposed after final client and grace.', 'Dead sockets do not pin clientCount.'],
    existingCoverage: ['Pi process eviction test', 'Pi bridge reload test', 'OpenCode reflection leak fixes'],
  },
  {
    id: 'ST-24',
    title: 'UI render smoke on desktop and mobile',
    tier: 'product-trace',
    priority: 'p1',
    agents: 'all',
    purpose: 'Wire-correct output must also look correct in the browser/mobile UI.',
    steps: ['Replay a canonical trace fixture into the app.', 'Capture desktop and mobile screenshots.', 'Inspect console warnings and layout metrics.'],
    assertions: ['No unhandled message warnings.', 'No overlapping text or overflowing tool headers.', 'Permission/question cards are actionable.', 'Artifacts open inline/download as expected.'],
    gaps: ['Needs Playwright-based replay harness.'],
  },
  {
    id: 'ST-25',
    title: 'security and path boundaries',
    tier: 'adapter-live',
    priority: 'p0',
    agents: 'all',
    purpose: 'File and session operations must not expose host secrets or accept unsafe ids/paths.',
    steps: ['Try path traversal filenames.', 'Try symlinked send_file paths.', 'Attach with an encoded path outside the allowed store.', 'Try large files.'],
    assertions: ['Uploads use basename/sanitization.', 'Session-qualified send_file rejects symlinks.', 'Attach containment rejects outside paths.', 'Large files return a safe notice instead of absolute path leakage.'],
    existingCoverage: ['Artifact session-isolation regression', 'Claude attach containment test', 'Pi hyphenated cwd/file IO test'],
  },
  {
    id: 'ST-26',
    title: 'observability and trace artifact contract',
    tier: 'synthetic',
    priority: 'p0',
    agents: 'all',
    purpose: 'Every scenario run must leave enough evidence to debug without rerunning live model behavior.',
    steps: ['Run a scenario.', 'Write trace.json, frames.ndjson, native transcript snapshot, files manifest, and screenshots if UI was involved.'],
    assertions: ['Output includes agent version, scenario id, skipped reason, assertions, redacted paths, and first failing frame.', 'A failed run is reproducible from saved fixtures where possible.'],
    gaps: ['This catalog defines the contract; the recorder implementation is next.'],
  },
  {
    id: 'ST-27',
    title: 'observe plus drive ownership boundary',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'Opening a session in Observe must be read-only; Drive must be an explicit app-owned continuation unless true sync is active.',
    steps: ['Discover an observe-first session.', 'Attach read-only Observe.', 'Attempt a mutation and verify it is rejected.', 'Attach with explicit Drive/resume.', 'Send a prompt and verify app-owned output/history.', 'Check terminal sync is not falsely active.'],
    assertions: ['Observe does not accept prompts, approvals, questions, uploads, commands, or interrupts.', 'Drive uses a distinct owner from observe and updates roster ownership.', 'Non-true-sync Drive is labelled as continuation/controller, not same terminal runtime.'],
    existingCoverage: ['scripts/broker/tests_traces/opencode-private-observe-drive-trace.ts', 'scripts/broker/tests_traces/opencode-real-run-drive-trace.ts', 'packages/typescript/adapters/pi/test/test-pi-observe.ts', 'packages/typescript/broker/test/codex/rollout.ts', 'scripts/broker/tests_traces/codex-surface-contract-trace.ts', 'packages/typescript/adapters/claude/test/test-claude-resume.ts'],
  },
  {
    id: 'ST-28',
    title: 'per-agent Codex sync enabler (SUPERSEDES the deleted control-mode picker)',
    tier: 'product-trace',
    priority: 'p0',
    agents: ['codex'],
    purpose: 'Sync Refactor (D13/D15/D17/FU-3): the global control-mode picker + /api/broker/control-mode are DELETED. Codex sync is enabled per-agent via POST /api/agents/codex/sync, persisted to setup-state.json, and applied pre-start so a fresh broker needs no restart; a one-time restart happens only when toggling against a running broker.',
    steps: ['Start a broker with Codex sync OFF.', 'GET /api/agents/codex/sync reports enabled:false.', 'POST {enabled:true} persists to setup-state.json and (against a running broker) schedules a one-time restart.', 'A fresh broker started with persisted codex=true comes up sync-ON with NO restart (FU-3).', 'The deleted /api/broker/control-mode endpoint is never called and #controlMode is absent from the DOM.'],
    assertions: ['GET enabler reports enabled:false at boot.', 'POST enabler persists agents.codex and returns restartRequired against a running observe-broker (dry-run).', 'Pre-start: persisted codex=true → health.codexSyncServer:true + supportsLiveAttach:true, no restart.', 'No #controlMode/#drive/#sync in the real DOM; exactly one #control button.'],
    existingCoverage: ['packages/typescript/broker/test/codex/broker-control-mode.ts', 'scripts/broker/tests_traces/sync-refactor-dom-probe.ts'],
  },
  {
    id: 'ST-29',
    title: 'native task-list state render surface',
    tier: 'product-trace',
    priority: 'p0',
    agents: 'all',
    purpose: 'Native todo/plan/task-list state must render as one canonical task-list panel instead of noisy raw tool cards.',
    steps: ['Seed or capture a native todo/task-list event.', 'Attach through the broker.', 'Record native evidence and broker WebSocket history/live frames.', 'Verify the shared UI-facing task-list-state frame.'],
    assertions: ['Exactly one canonical task-list-state panel is emitted for the latest native list.', 'Item text and statuses match the native source after normalization.', 'Raw native todo/update-plan tool-call and tool-result cards are suppressed when a structured task list is available.'],
    existingCoverage: ['scripts/broker/tests_traces/opencode-private-observe-drive-trace.ts', 'scripts/broker/tests_traces/opencode-real-run-drive-trace.ts', 'packages/typescript/broker/test/codex/rollout.ts', 'scripts/broker/tests_traces/codex-surface-contract-trace.ts'],
    gaps: ['Claude Code TodoWrite/task-list mapping still needs native-sample-backed adapter and trace coverage.', 'Codex app-server live update_plan shape still needs verification before live task-list mapping is claimed.'],
  },
  {
    id: 'ST-30',
    title: 'plan mode enter edit approve exit',
    tier: 'product-trace',
    priority: 'p1',
    agents: ['claude', 'opencode', 'codex'],
    purpose: 'Plan-mode UX must not be confused with normal permission-mode display. Native entry hooks are per-agent, while the cross-agent product lifecycle is approve/revise/exit on canonical plan task lists through semantic plan-action frames.',
    steps: ['Attach a drivable or otherwise prompt-capable session.', 'Enter the agent plan mode or nearest native equivalent when it exists.', 'Trigger or render a plan-like task list.', 'Approve, revise, or exit the plan from the app.', 'Verify native entry/protocol state where available and visible app state everywhere.'],
    assertions: ['Plan mode is visible in the statusline or mode picker when native state reports it.', 'Plan lifecycle controls are enabled only when the session can accept prompts.', 'Approving or editing a plan leaves the app as kind:"plan-action", not an accidental plain prompt.', 'The broker applies the same mutation/prompt gates before routing plan-action to adapter-native respondPlan() or structured fallback text.', 'Exiting plan mode leaves the composer/pickers in the correct actionability state.'],
    existingCoverage: ['claude-surface-contract-trace.ts proves app-selected Claude plan launches as --permission-mode plan', 'opencode-display-trace.ts proves app-selected OpenCode plan rides as native agent:"plan"', 'Codex task-list/update_plan display traces', 'test-web-ui-components.ts proves approve/revise/exit plan controls emit semantic plan-action frames', 'test-web-ui-static.ts guards the core/broker/app plan-action route'],
    gaps: ['Codex generated plan/default collaboration mode is not yet wired as an adapter-native hook; update_plan is display state, not native enter/edit/approve/exit.', 'No adapter-native respondPlan() is claimed until a real native plan-control channel is verified.'],
  },
  {
    id: 'ST-31',
    title: 'Claude tmux-visible TUI ornaments',
    tier: 'product-trace',
    priority: 'p1',
    agents: ['claude'],
    purpose: 'The tmux monitor line should either normalize Claude-only visible ornaments into canonical frames or explicitly mark them TUI-only so they are not silently missing from the app.',
    steps: ['Run a real Claude TUI in tmux.', 'Trigger selected-editor-lines, diagnostics summary, thought timer, recap, long-running/crunched timer, trace checklist, and TodoWrite states where available.', 'Capture tmux pane output and the broker/app transcript.', 'Compare each visible ornament against app frames and DOM.'],
    assertions: ['Every captured ornament is either rendered in the app through a canonical frame or documented as intentionally TUI-only.', 'Todo ongoing/complete/open states render as one task-list-state panel.', 'Runtime/thought/checklist text does not pollute normal assistant output unless it is a real model message.', 'Trace artifacts include the tmux capture so failures can be reviewed without rerunning the model.'],
    existingCoverage: ['docs/protocol/adapter-support.md', 'scripts/broker/tests_traces/claude-workflow-activity-trace.ts', 'scripts/broker/tests_traces/claude-runtime-trace.ts', 'scripts/broker/tests_traces/claude-app-answer-real-tui-trace.ts'],
    gaps: ['No broad product trace maps the listed Claude TUI ornaments end-to-end today.'],
  },
  {
    id: 'ST-32',
    title: 'terminal owner disappearance and sync degradation',
    tier: 'product-trace',
    priority: 'p0',
    agents: ['opencode', 'codex', 'pi'],
    purpose: 'If the terminal/shared-server/daemon owner disappears, the app must stop claiming stale true-sync or app-drivable ownership.',
    steps: ['Attach to an active sync/session owner.', 'Kill or disconnect the owner.', 'Observe pushed session frames and roster overlay.', 'Attempt a crafted prompt after downgrade.'],
    assertions: ['Attached clients receive an honest ended/degraded/observe session state.', '`terminalSync.active` is false after owner loss.', 'Prompts are rejected at the broker boundary unless a new Drive owner is explicitly established.'],
    existingCoverage: ['packages/typescript/broker/test/pi/test-pi-bridge-reload.ts', 'scripts/broker/tests_traces/opencode-owner-degrade-trace.ts', 'scripts/broker/tests_traces/codex-true-sync-trace.ts'],
  },
  {
    id: 'ST-33',
    title: 'durable history pagination and delivery replay',
    tier: 'synthetic',
    priority: 'p0',
    agents: 'all',
    purpose: 'Prove older history, local-commit checkpoints, and mutation retry remain safe across reconnect and broker restart.',
    steps: ['Attach to a history longer than the broker cap.', 'Load backward pages to end-of-history.', 'Ack only after the local transcript/projection transaction commits.', 'Reconnect/restart and replay identical and conflicting clientMessageId mutations.', 'Exercise rewritten, gone, and malformed cursors.'],
    assertions: ['Pages are chronological with exact boundaries and no old task/goal/activity/reset projection resurrection.', 'Ack advances only the identity/session-scoped durable checkpoint; nack does not.', 'Identical terminal outcomes replay across restart without a second dispatch.', 'Conflicting clientMessageId reuse and crash-unknown outcomes fail with stable typed codes.'],
    existingCoverage: ['packages/typescript/broker/test/broker/test-history-cap.ts', 'packages/typescript/broker/test/broker/test-protocol-journal.ts', 'packages/typescript/broker/test/broker/test-protocol-hardening.ts'],
  },
  {
    id: 'ST-34',
    title: 'durable scheduled-send controls',
    tier: 'synthetic',
    priority: 'p0',
    agents: 'all',
    purpose: 'Prove schedule edits, lifecycle actions, cron, retry, and quota recovery stay authenticated, revision-safe, and durable across restart.',
    steps: ['Create legacy and arbitrary-cron schedules.', 'Edit with current and stale revisions.', 'Exercise pause, resume, run-now, and quota recovery.', 'Restart during a typed retry.', 'Apply the missed-fire boundary to an overdue retry.'],
    assertions: ['Full prompt-bearing schedule routes require authentication.', 'Stale edits and invalid state transitions fail with stable codes.', 'Retry counters and terminal outcomes survive restart without duplicate attention.', 'Generic error text cannot activate quota retry or recovery.', 'Existing-session schedules remain one-shot and missed occurrences never retry.'],
    existingCoverage: ['packages/typescript/broker/test/broker/test-schedule-store.ts', 'packages/typescript/broker/test/broker/test-broker-auth.ts'],
    gaps: ['No current adapter emits native synchronous quota-class evidence at prompt handoff; recover-quota therefore remains unavailable in real adapter delivery until that evidence exists.'],
  },
];

export function scenariosFor(agent?: AgentId): TraceScenario[] {
  if (!agent) return TRACE_SCENARIOS;
  return TRACE_SCENARIOS.filter((s) => s.agents === 'all' || s.agents.includes(agent));
}
