// Reviewed public theme source. Update together with the theme registry.
// ignore_for_file: lines_longer_than_80_chars
import 'package:cosyncing_client/src/design/app_tokens.dart';
import 'package:cosyncing_client/src/design/theme_spec.dart';
import 'package:flutter/material.dart';

/// Cyber Amber — A retro-futuristic glowing amber workspace combining a warm slate/black canvas with rich amber terminal typography. Offers a warm sand/manila paper light mode variant.
const ThemeSpec cyberAmberTheme = ThemeSpec(
  id: 'cyber-amber',
  name: 'Cyber Amber',
  description:
      'A retro-futuristic glowing amber workspace combining a warm slate/black canvas with rich amber terminal typography. Offers a warm sand/manila paper light mode variant.',
  light: AppTokens(
    canvas: Color(0xFFFAF6EE),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFF0EADE),
    separator: Color(0xFFE3DAC9),
    textPrimary: Color(0xFF29211A),
    textSecondary: Color(0xFF6E5D4F),
    textTertiary: Color(0xFF9C8C7E),
    accent: Color(0xFF9E6600),
    accentInk: Color(0xFFFFFFFF),
    statusWorking: Color(0xFF0E7490),
    statusNeedsInput: Color(0xFF9E6600),
    statusIdle: Color(0xFF78716C),
    statusError: Color(0xFFB91C1C),
    toolOpencode: Color(0xFF047857),
    toolCodex: Color(0xFF6D28D9),
    toolClaude: Color(0xFFBE185D),
    toolPi: Color(0xFF0369A1),
    toolOmp: Color(0xFFC2410C),
    diffAddText: Color(0xFF166534),
    diffAddSurface: Color(0xFFE6F4EA),
    diffRemoveText: Color(0xFFB91C1C),
    diffRemoveSurface: Color(0xFFFBE9E9),
    syntaxKeyword: Color(0xFF8A5000),
    syntaxString: Color(0xFF047857),
    syntaxNumber: Color(0xFF0369A1),
    syntaxComment: Color(0xFF6E5D4F),
    syntaxLiteral: Color(0xFFA3341B),
    radiusXs: 4,
    radiusSm: 4,
    radiusMd: 6,
    radiusLg: 8,
  ),
  dark: AppTokens(
    canvas: Color(0xFF0F0D0A),
    surface: Color(0xFF1A1612),
    surface2: Color(0xFF26201A),
    separator: Color(0xFF3B3026),
    textPrimary: Color(0xFFFFB000),
    textSecondary: Color(0xFFD48F00),
    textTertiary: Color(0xFF8A5E00),
    accent: Color(0xFFFFC000),
    accentInk: Color(0xFF0F0D0A),
    statusWorking: Color(0xFF00E5FF),
    statusNeedsInput: Color(0xFFFFD600),
    statusIdle: Color(0xFF8A8A8A),
    statusError: Color(0xFFFF1744),
    toolOpencode: Color(0xFF34D399),
    toolCodex: Color(0xFFA78BFA),
    toolClaude: Color(0xFFF472B6),
    toolPi: Color(0xFF38BDF8),
    toolOmp: Color(0xFFFB923C),
    diffAddText: Color(0xFF6EE7A8),
    diffAddSurface: Color(0xFF13251B),
    diffRemoveText: Color(0xFFF7A3A3),
    diffRemoveSurface: Color(0xFF2A1618),
    syntaxKeyword: Color(0xFFFFC966),
    syntaxString: Color(0xFF4EDBA4),
    syntaxNumber: Color(0xFF4FC9F5),
    syntaxComment: Color(0xFFA08B72),
    syntaxLiteral: Color(0xFFFF9E64),
    radiusXs: 4,
    radiusSm: 4,
    radiusMd: 6,
    radiusLg: 8,
  ),
);
