// Reviewed public theme source. Update together with the theme registry.
// ignore_for_file: lines_longer_than_80_chars
import 'package:cosyncing_client/src/design/app_tokens.dart';
import 'package:cosyncing_client/src/design/theme_spec.dart';
import 'package:flutter/material.dart';

/// Flat White Minimalist — An ultra-flat, near-pure-white space leveraging bold type weight and empty breathing room rather than borders, shadows, or colors.
const ThemeSpec flatWhiteMinimalistTheme = ThemeSpec(
  id: 'flat-white-minimalist',
  name: 'Flat White Minimalist',
  description:
      'An ultra-flat, near-pure-white space leveraging bold type weight and empty breathing room rather than borders, shadows, or colors.',
  light: AppTokens(
    canvas: Color(0xFFFCFCFC),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFF5F5F5),
    separator: Color(0xFFEAEAEA),
    textPrimary: Color(0xFF000000),
    textSecondary: Color(0xFF666666),
    textTertiary: Color(0xFF8C8C8C),
    accent: Color(0xFF000000),
    accentInk: Color(0xFFFFFFFF),
    statusWorking: Color(0xFF2563EB),
    statusNeedsInput: Color(0xFFB44409),
    statusIdle: Color(0xFF737373),
    statusError: Color(0xFFDC2626),
    toolOpencode: Color(0xFF059669),
    toolCodex: Color(0xFF7C3AED),
    toolClaude: Color(0xFFDB2777),
    toolPi: Color(0xFF0284C7),
    diffAddText: Color(0xFF166534),
    diffAddSurface: Color(0xFFE6F4EA),
    diffRemoveText: Color(0xFFB91C1C),
    diffRemoveSurface: Color(0xFFFBE9E9),
    syntaxKeyword: Color(0xFF6D28D9),
    syntaxString: Color(0xFF047857),
    syntaxNumber: Color(0xFF0369A1),
    syntaxComment: Color(0xFF666666),
    syntaxLiteral: Color(0xFFA34E00),
    radiusXs: 0,
    radiusSm: 0,
    radiusMd: 0,
    radiusLg: 0,
  ),
  dark: AppTokens(
    canvas: Color(0xFF0A0A0A),
    surface: Color(0xFF101010),
    surface2: Color(0xFF1A1A1A),
    separator: Color(0xFF262626),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFA3A3A3),
    textTertiary: Color(0xFF676767),
    accent: Color(0xFFFFFFFF),
    accentInk: Color(0xFF0A0A0A),
    statusWorking: Color(0xFF3B82F6),
    statusNeedsInput: Color(0xFFF97316),
    statusIdle: Color(0xFFA3A3A3),
    statusError: Color(0xFFEF4444),
    toolOpencode: Color(0xFF34D399),
    toolCodex: Color(0xFFA78BFA),
    toolClaude: Color(0xFFF472B6),
    toolPi: Color(0xFF38BDF8),
    diffAddText: Color(0xFF6EE7A8),
    diffAddSurface: Color(0xFF13251B),
    diffRemoveText: Color(0xFFF7A3A3),
    diffRemoveSurface: Color(0xFF2A1618),
    syntaxKeyword: Color(0xFFA78BFA),
    syntaxString: Color(0xFF34D399),
    syntaxNumber: Color(0xFF38BDF8),
    syntaxComment: Color(0xFFA3A3A3),
    syntaxLiteral: Color(0xFFF0A048),
    radiusXs: 0,
    radiusSm: 0,
    radiusMd: 0,
    radiusLg: 0,
  ),
);
