// Reviewed public theme source. Update together with the theme registry.
// ignore_for_file: lines_longer_than_80_chars
import 'package:cosyncing_client/src/design/app_tokens.dart';
import 'package:cosyncing_client/src/design/theme_spec.dart';
import 'package:flutter/material.dart';

/// Graphite Minimalist — A quiet, high-contrast monochrome space leveraging cool graphite scales and refined typographic spacing for zero-distraction code driving.
const ThemeSpec graphiteMinimalistTheme = ThemeSpec(
  id: 'graphite-minimalist',
  name: 'Graphite Minimalist',
  description:
      'A quiet, high-contrast monochrome space leveraging cool graphite scales and refined typographic spacing for zero-distraction code driving.',
  light: AppTokens(
    canvas: Color(0xFFF8FAFC),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFF1F5F9),
    separator: Color(0xFFE2E8F0),
    textPrimary: Color(0xFF0F172A),
    textSecondary: Color(0xFF475569),
    textTertiary: Color(0xFF596675),
    accent: Color(0xFF0F172A),
    accentInk: Color(0xFFFFFFFF),
    statusWorking: Color(0xFF2563EB),
    statusNeedsInput: Color(0xFFC2410C),
    statusIdle: Color(0xFF526071),
    statusError: Color(0xFFE11D48),
    toolOpencode: Color(0xFF10B981),
    toolCodex: Color(0xFF8B5CF6),
    toolClaude: Color(0xFFEC4899),
    toolPi: Color(0xFF0EA5E9),
    toolOmp: Color(0xFFC2410C),
    diffAddText: Color(0xFF166534),
    diffAddSurface: Color(0xFFE6F4EA),
    diffRemoveText: Color(0xFFB91C1C),
    diffRemoveSurface: Color(0xFFFBE9E9),
    syntaxKeyword: Color(0xFF6D28D9),
    syntaxString: Color(0xFF047857),
    syntaxNumber: Color(0xFF0369A1),
    syntaxComment: Color(0xFF556070),
    syntaxLiteral: Color(0xFFA34E00),
    radiusXs: 2,
    radiusSm: 4,
    radiusMd: 6,
    radiusLg: 8,
  ),
  dark: AppTokens(
    canvas: Color(0xFF0B0F19),
    surface: Color(0xFF121826),
    surface2: Color(0xFF1E293B),
    separator: Color(0xFF334155),
    textPrimary: Color(0xFFF8FAFC),
    textSecondary: Color(0xFF94A3B8),
    textTertiary: Color(0xFF616D7E),
    accent: Color(0xFFF8FAFC),
    accentInk: Color(0xFF0F172A),
    statusWorking: Color(0xFF3B82F6),
    statusNeedsInput: Color(0xFFF97316),
    statusIdle: Color(0xFF64748B),
    statusError: Color(0xFFF43F5E),
    toolOpencode: Color(0xFF34D399),
    toolCodex: Color(0xFFA78BFA),
    toolClaude: Color(0xFFF472B6),
    toolPi: Color(0xFF38BDF8),
    toolOmp: Color(0xFFFB923C),
    diffAddText: Color(0xFF6EE7A8),
    diffAddSurface: Color(0xFF13251B),
    diffRemoveText: Color(0xFFF7A3A3),
    diffRemoveSurface: Color(0xFF2A1618),
    syntaxKeyword: Color(0xFFA78BFA),
    syntaxString: Color(0xFF34D399),
    syntaxNumber: Color(0xFF38BDF8),
    syntaxComment: Color(0xFF94A3B8),
    syntaxLiteral: Color(0xFFF0A048),
    radiusXs: 2,
    radiusSm: 4,
    radiusMd: 6,
    radiusLg: 8,
  ),
);
