// Reviewed public theme source. Update together with the theme registry.
// ignore_for_file: lines_longer_than_80_chars
import 'package:cosyncing_client/src/design/app_tokens.dart';
import 'package:cosyncing_client/src/design/theme_spec.dart';
import 'package:flutter/material.dart';

/// Nordic Warmth — A warm, organic canvas inspired by Nordic wood and clay, pairing soft cozy neutrals with deep indigo/amber semantic accents to reduce visual fatigue.
const ThemeSpec nordicWarmthTheme = ThemeSpec(
  id: 'nordic-warmth',
  name: 'Nordic Warmth',
  description:
      'A warm, organic canvas inspired by Nordic wood and clay, pairing soft cozy neutrals with deep indigo/amber semantic accents to reduce visual fatigue.',
  light: AppTokens(
    canvas: Color(0xFFFBFBFA),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFF4F3F0),
    separator: Color(0xFFEBE8E2),
    textPrimary: Color(0xFF2E251E),
    textSecondary: Color(0xFF70655B),
    textTertiary: Color(0xFF7E7065),
    accent: Color(0xFF4F46E5),
    accentInk: Color(0xFFFFFFFF),
    accentSurface: Color(0xFFE4E2EF),
    statusWorking: Color(0xFF0E7490),
    statusNeedsInput: Color(0xFFB45309),
    statusIdle: Color(0xFF78716C),
    statusError: Color(0xFFDC2626),
    toolOpencode: Color(0xFF047857),
    toolCodex: Color(0xFF6D28D9),
    toolClaude: Color(0xFFBE185D),
    toolPi: Color(0xFF0369A1),
    toolOmp: Color(0xFFC2410C),
    diffAddText: Color(0xFF166534),
    diffAddSurface: Color(0xFFE6F4EA),
    diffRemoveText: Color(0xFFB91C1C),
    diffRemoveSurface: Color(0xFFFBE9E9),
    syntaxKeyword: Color(0xFF5B48E0),
    syntaxString: Color(0xFF047857),
    syntaxNumber: Color(0xFF0369A1),
    syntaxComment: Color(0xFF70655B),
    syntaxLiteral: Color(0xFFA34E00),
    radiusXs: 6,
    radiusSm: 8,
    radiusMd: 12,
    radiusLg: 16,
  ),
  dark: AppTokens(
    canvas: Color(0xFF181614),
    surface: Color(0xFF221E1B),
    surface2: Color(0xFF2E2925),
    separator: Color(0xFF3C3631),
    textPrimary: Color(0xFFF5F2EB),
    textSecondary: Color(0xFFA89F95),
    textTertiary: Color(0xFF766F69),
    accent: Color(0xFF818CF8),
    accentInk: Color(0xFF181614),
    accentSurface: Color(0xFF393640),
    statusWorking: Color(0xFF22D3EE),
    statusNeedsInput: Color(0xFFFBBF24),
    statusIdle: Color(0xFFA8A29E),
    statusError: Color(0xFFF87171),
    toolOpencode: Color(0xFF34D399),
    toolCodex: Color(0xFFA78BFA),
    toolClaude: Color(0xFFF472B6),
    toolPi: Color(0xFF38BDF8),
    toolOmp: Color(0xFFFB923C),
    diffAddText: Color(0xFF6EE7A8),
    diffAddSurface: Color(0xFF13251B),
    diffRemoveText: Color(0xFFF7A3A3),
    diffRemoveSurface: Color(0xFF2A1618),
    syntaxKeyword: Color(0xFFA8A2F5),
    syntaxString: Color(0xFF34D399),
    syntaxNumber: Color(0xFF38BDF8),
    syntaxComment: Color(0xFFA89F95),
    syntaxLiteral: Color(0xFFF0A048),
    radiusXs: 6,
    radiusSm: 8,
    radiusMd: 12,
    radiusLg: 16,
  ),
);
