// Reviewed public theme source. Update together with the theme registry.
// ignore_for_file: lines_longer_than_80_chars
import 'package:cosyncing_client/src/design/app_tokens.dart';
import 'package:cosyncing_client/src/design/theme_spec.dart';
import 'package:flutter/material.dart';

/// Royal Navy — A premium maritime-inspired developer environment built around rich deep navy blues, icy steel metallic grays, and glowing royal blue accents.
const ThemeSpec royalNavyTheme = ThemeSpec(
  id: 'royal-navy',
  name: 'Royal Navy',
  description:
      'A premium maritime-inspired developer environment built around rich deep navy blues, icy steel metallic grays, and glowing royal blue accents.',
  light: AppTokens(
    canvas: Color(0xFFF0F4FA),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFE1EBF5),
    separator: Color(0xFFC9D8E6),
    textPrimary: Color(0xFF0D1E3D),
    textSecondary: Color(0xFF3B5580),
    textTertiary: Color(0xFF6B84A8),
    accent: Color(0xFF1D4ED8),
    accentInk: Color(0xFFFFFFFF),
    statusWorking: Color(0xFF047857),
    statusNeedsInput: Color(0xFFB45309),
    statusIdle: Color(0xFF64748B),
    statusError: Color(0xFFB91C1C),
    toolOpencode: Color(0xFF047857),
    toolCodex: Color(0xFF6D28D9),
    toolClaude: Color(0xFFBE185D),
    toolPi: Color(0xFF0369A1),
    toolOmp: Color(0xFFC2410C),
    diffAddText: Color(0xFF166534),
    diffAddSurface: Color(0xFFE6F4EA),
    diffRemoveText: Color(0xFFB91C1C),
    diffRemoveSurface: Color(0xFFFBE9E9),
    syntaxKeyword: Color(0xFF6D28D9),
    syntaxString: Color(0xFF0B6B3F),
    syntaxNumber: Color(0xFF0369A1),
    syntaxComment: Color(0xFF3B5580),
    syntaxLiteral: Color(0xFFA34E00),
    radiusXs: 4,
    radiusSm: 6,
    radiusMd: 8,
    radiusLg: 12,
  ),
  dark: AppTokens(
    canvas: Color(0xFF0A0E1A),
    surface: Color(0xFF121A30),
    surface2: Color(0xFF1C294A),
    separator: Color(0xFF2B3B66),
    textPrimary: Color(0xFFE6F0FF),
    textSecondary: Color(0xFFA3C2FA),
    textTertiary: Color(0xFF5A7BB5),
    accent: Color(0xFF3B82F6),
    accentInk: Color(0xFFFFFFFF),
    statusWorking: Color(0xFF10B981),
    statusNeedsInput: Color(0xFFF59E0B),
    statusIdle: Color(0xFF64748B),
    statusError: Color(0xFFEF4444),
    toolOpencode: Color(0xFF34D399),
    toolCodex: Color(0xFFA78BFA),
    toolClaude: Color(0xFFF472B6),
    toolPi: Color(0xFF38BDF8),
    toolOmp: Color(0xFFFB923C),
    diffAddText: Color(0xFF6EE7A8),
    diffAddSurface: Color(0xFF13251B),
    diffRemoveText: Color(0xFFF7A3A3),
    diffRemoveSurface: Color(0xFF2A1618),
    syntaxKeyword: Color(0xFFB79DFC),
    syntaxString: Color(0xFF3FD9A0),
    syntaxNumber: Color(0xFF52C7FA),
    syntaxComment: Color(0xFF93A8CC),
    syntaxLiteral: Color(0xFFF5A85A),
    radiusXs: 4,
    radiusSm: 6,
    radiusMd: 8,
    radiusLg: 12,
  ),
);
