// Reviewed public theme source. Update together with the theme registry.
// ignore_for_file: lines_longer_than_80_chars
import 'package:cosyncing_client/src/design/app_tokens.dart';
import 'package:cosyncing_client/src/design/theme_spec.dart';
import 'package:flutter/material.dart';

/// Soft Minimalist — A soft, clean, open workspace using gentle off-whites and cool zinc slates. Rejects heavy card boxes and high-contrast lines in favor of extremely soft rounded corners, airy margins, and gentle tonal background changes.
const ThemeSpec softMinimalistTheme = ThemeSpec(
  id: 'soft-minimalist',
  name: 'Soft Minimalist',
  description:
      'A soft, clean, open workspace using gentle off-whites and cool zinc slates. Rejects heavy card boxes and high-contrast lines in favor of extremely soft rounded corners, airy margins, and gentle tonal background changes.',
  light: AppTokens(
    canvas: Color(0xFFF4F4F6),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFEAEAEE),
    separator: Color(0xFFE2E2E8),
    textPrimary: Color(0xFF1E1E24),
    textSecondary: Color(0xFF626270),
    textTertiary: Color(0xFF9090A0),
    accent: Color(0xFF4F46E5),
    accentInk: Color(0xFFFFFFFF),
    accentSurface: Color(0xFFDBDAED),
    statusWorking: Color(0xFF096F9C),
    statusNeedsInput: Color(0xFF9E5704),
    statusIdle: Color(0xFF71717A),
    statusError: Color(0xFFE11D48),
    toolOpencode: Color(0xFF047857),
    toolCodex: Color(0xFF6D28D9),
    toolClaude: Color(0xFFBE185D),
    toolPi: Color(0xFF0369A1),
    toolOmp: Color(0xFFC2410C),
    diffAddText: Color(0xFF166534),
    diffAddSurface: Color(0xFFE6F4EA),
    diffRemoveText: Color(0xFFB91C1C),
    diffRemoveSurface: Color(0xFFFBE9E9),
    syntaxKeyword: Color(0xFF6D28D9),
    syntaxString: Color(0xFF047857),
    syntaxNumber: Color(0xFF0369A1),
    syntaxComment: Color(0xFF5C5C6A),
    syntaxLiteral: Color(0xFFA34E00),
    radiusXs: 6,
    radiusSm: 10,
    radiusMd: 16,
    radiusLg: 24,
  ),
  dark: AppTokens(
    canvas: Color(0xFF0F0F12),
    surface: Color(0xFF16161B),
    surface2: Color(0xFF202028),
    separator: Color(0xFF2A2A35),
    textPrimary: Color(0xFFF1F1F5),
    textSecondary: Color(0xFFA0A0B0),
    textTertiary: Color(0xFF6A6A79),
    accent: Color(0xFF818CF8),
    accentInk: Color(0xFF0F0F12),
    accentSurface: Color(0xFF2D2E43),
    statusWorking: Color(0xFF38BDF8),
    statusNeedsInput: Color(0xFFFBBF24),
    statusIdle: Color(0xFFA1A1AA),
    statusError: Color(0xFFFB7185),
    toolOpencode: Color(0xFF34D399),
    toolCodex: Color(0xFFA78BFA),
    toolClaude: Color(0xFFF472B6),
    toolPi: Color(0xFF38BDF8),
    toolOmp: Color(0xFFFB923C),
    diffAddText: Color(0xFF6EE7A8),
    diffAddSurface: Color(0xFF13251B),
    diffRemoveText: Color(0xFFF7A3A3),
    diffRemoveSurface: Color(0xFF2A1618),
    syntaxKeyword: Color(0xFFA78BFA),
    syntaxString: Color(0xFF34D399),
    syntaxNumber: Color(0xFF38BDF8),
    syntaxComment: Color(0xFFA0A0B0),
    syntaxLiteral: Color(0xFFF0A048),
    radiusXs: 6,
    radiusSm: 10,
    radiusMd: 16,
    radiusLg: 24,
  ),
);
