// Reviewed public theme source. Update together with the theme registry.
// ignore_for_file: lines_longer_than_80_chars
import 'package:cosyncing_client/src/design/app_tokens.dart';
import 'package:cosyncing_client/src/design/theme_spec.dart';
import 'package:flutter/material.dart';

/// Teal Obsidian — An evolution of the heritage teal accent against a deep obsidian mineral palette for focused, low-strain developer operations.
const ThemeSpec tealObsidianTheme = ThemeSpec(
  id: 'teal-obsidian',
  name: 'Teal Obsidian',
  description:
      'An evolution of the heritage teal accent against a deep obsidian mineral palette for focused, low-strain developer operations.',
  light: AppTokens(
    canvas: Color(0xFFF2F5F4),
    surface: Color(0xFFFFFFFF),
    surface2: Color(0xFFE6ECEB),
    separator: Color(0xFFDBE3E1),
    textPrimary: Color(0xFF1E2927),
    textSecondary: Color(0xFF5F7370),
    textTertiary: Color(0xFF627572),
    accent: Color(0xFF0F766E),
    accentInk: Color(0xFFFFFFFF),
    statusWorking: Color(0xFF0D9488),
    statusNeedsInput: Color(0xFFB45309),
    statusIdle: Color(0xFF4B5563),
    statusError: Color(0xFFDC2626),
    toolOpencode: Color(0xFF047857),
    toolCodex: Color(0xFF6D28D9),
    toolClaude: Color(0xFFBE185D),
    toolPi: Color(0xFF0369A1),
    toolOmp: Color(0xFFC2410C),
    diffAddText: Color(0xFF166534),
    diffAddSurface: Color(0xFFE6F4EA),
    diffRemoveText: Color(0xFFB91C1C),
    diffRemoveSurface: Color(0xFFFBE9E9),
    syntaxKeyword: Color(0xFF6D28D9),
    syntaxString: Color(0xFF047857),
    syntaxNumber: Color(0xFF0369A1),
    syntaxComment: Color(0xFF556A66),
    syntaxLiteral: Color(0xFFA34E00),
    radiusXs: 4,
    radiusSm: 6,
    radiusMd: 8,
    radiusLg: 12,
  ),
  dark: AppTokens(
    canvas: Color(0xFF0B0E14),
    surface: Color(0xFF121722),
    surface2: Color(0xFF1B2332),
    separator: Color(0xFF232F42),
    textPrimary: Color(0xFFE2E8F0),
    textSecondary: Color(0xFF94A3B8),
    textTertiary: Color(0xFF5F6B7C),
    accent: Color(0xFF2DD4BF),
    accentInk: Color(0xFF0B0E14),
    statusWorking: Color(0xFF14B8A6),
    statusNeedsInput: Color(0xFFF59E0B),
    statusIdle: Color(0xFF9CA3AF),
    statusError: Color(0xFFEF4444),
    toolOpencode: Color(0xFF34D399),
    toolCodex: Color(0xFFA78BFA),
    toolClaude: Color(0xFFF472B6),
    toolPi: Color(0xFF38BDF8),
    toolOmp: Color(0xFFFB923C),
    diffAddText: Color(0xFF6EE7A8),
    diffAddSurface: Color(0xFF13251B),
    diffRemoveText: Color(0xFFF7A3A3),
    diffRemoveSurface: Color(0xFF2A1618),
    syntaxKeyword: Color(0xFFA78BFA),
    syntaxString: Color(0xFF34D399),
    syntaxNumber: Color(0xFF38BDF8),
    syntaxComment: Color(0xFF8B9BB0),
    syntaxLiteral: Color(0xFFF0A048),
    radiusXs: 4,
    radiusSm: 6,
    radiusMd: 8,
    radiusLg: 12,
  ),
);
