import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

export const CLIENT_CONTRACT_SOURCE_FILES = [
  'packages/typescript/protocol/src/product.ts',
  'packages/typescript/protocol/src/index.ts',
] as const;

const PRODUCT_IMPORT = "import { PRODUCT_IDENTITY } from './product.ts';";
const PRODUCT_REEXPORT = "export { PRODUCT_IDENTITY, type ProductIdentity } from './product.ts';";

function normalizedSource(path: string): string {
  return readFileSync(path, 'utf8').replaceAll('\r\n', '\n').trimEnd();
}

function removeSingleLine(source: string, line: string, label: string): string {
  const lines = source.split('\n');
  const matches = lines.flatMap((value, index) => value === line ? [index] : []);
  if (matches.length !== 1) {
    throw new Error(`client contract export expected one ${label}; found ${matches.length}`);
  }
  lines.splice(matches[0]!, 1);
  return lines.join('\n');
}

/**
 * Render the complete public client contract as one import-free TypeScript snapshot.
 *
 * The Flutter repository stores this text verbatim. Keeping the source list here means a change to
 * product identity or the main core surface changes the same snapshot and cannot bypass drift checks.
 */
export function renderClientContract(root = resolve(import.meta.dir, '../../..')): string {
  const [productRelative, indexRelative] = CLIENT_CONTRACT_SOURCE_FILES;
  const productSource = normalizedSource(resolve(root, productRelative));
  let indexSource = normalizedSource(resolve(root, indexRelative));
  indexSource = removeSingleLine(indexSource, PRODUCT_IMPORT, 'PRODUCT_IDENTITY import');
  indexSource = removeSingleLine(indexSource, PRODUCT_REEXPORT, 'PRODUCT_IDENTITY re-export');

  const body = `${productSource}\n\n${indexSource.trimStart()}\n`;
  if (/\b(?:import|export)\b[^'"\n]*\bfrom\s*['"]\.\.?\//.test(body)
      || /\bimport\s*['"]\.\.?\//.test(body)) {
    throw new Error('client contract export is not self-contained: a relative module reference remains');
  }

  const sources = CLIENT_CONTRACT_SOURCE_FILES.map((path) => `// - ${path}`).join('\n');
  return `// GENERATED by scripts/broker/export-client-contract.ts. DO NOT EDIT.\n`
    + `// Flattened broker contract sources:\n${sources}\n\n${body}`;
}
