/**
 * `@cosyncing/acp-client` — a provider-neutral Agent Client Protocol (ACP)
 * JSON-RPC 2.0 stdio client. No cosyncing semantics, no repo imports.
 */
export {
  AcpClient,
  AcpRequestTimeoutError,
  AcpRpcError,
  type AcpClientOptions,
} from './client.ts';
export {
  AcpDispatcher,
  type AcpDispatchContext,
} from './dispatch.ts';
export {
  AcpChild,
  type AcpChildExit,
  type AcpChildOptions,
} from './spawn.ts';
export {
  ACP_EXTENSION_NAMESPACES,
  ACP_PROTOCOL_MAJOR,
  ACP_SESSION_UPDATE_KNOWN,
  JSON_RPC_ERROR,
  JSON_RPC_SERVER_ERROR_RANGE,
  JSON_RPC_VERSION,
  boundedTraceDetail,
  extensionNamespaceFor,
  isKnownErrorCode,
  normalizeProtocolVersion,
  stderrTraceSink,
  type AcpClientCapabilities,
  type AcpClientHooks,
  type AcpClientInfo,
  type AcpContentBlock,
  type AcpAuthenticateParams,
  type AcpAuthenticateResult,
  type AcpExtensionEvent,
  type AcpExtensionHook,
  type AcpExtensionNamespace,
  type AcpInitializeParams,
  type AcpInitializeResult,
  type AcpPermissionOption,
  type AcpPermissionOutcome,
  type AcpProtocolVersion,
  type AcpRequestPermissionParams,
  type AcpRequestPermissionResult,
  type AcpSessionListResult,
  type AcpSessionLoadParams,
  type AcpSessionLoadResult,
  type AcpSessionNewParams,
  type AcpSessionNewResult,
  type AcpSessionPromptParams,
  type AcpSessionPromptResult,
  type AcpSessionCloseParams,
  type AcpSessionCloseResult,
  type AcpSetConfigOptionParams,
  type AcpSetConfigOptionResult,
  type AcpSessionUpdate,
  type AcpSessionUpdateParams,
  type AcpTraceEvent,
  type AcpTraceKind,
  type AcpTraceSink,
  type JsonRpcErrorObject,
  type JsonRpcErrorResponse,
  type JsonRpcId,
  type JsonRpcNotification,
  type JsonRpcOutbound,
  type JsonRpcRequest,
  type JsonRpcResultResponse,
} from './types.ts';
